import type { Metadata } from 'next';
import './globals.css';
import SideNav from '@/common/sideNav/SideNav';
import Header from '@/common/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        <Header />
        <SideNav />
        <main>{children}</main>
      </body>
    </html>
  );
}
